In [2]:
import pandas as pd

In [3]:
generation_df = pd.read_csv(

    "../notebooks2/generation_metrics.csv"

)

generation_df

         pipeline   ROUGE_L      BLEU  BERTScore
0    Fusion GPT4o  0.297738  0.047550   0.858821
1  Hybrid Mistral  0.271151  0.038345   0.851480
2  Fusion Mistral  0.268982  0.039257   0.849840
3     Dense GPT4o  0.238544  0.031553   0.847399
4   Dense Mistral  0.243224  0.022643   0.847247
5   Fusion Llama3  0.243026  0.035281   0.845276
6   Hybrid Llama3  0.238935  0.037905   0.843333
7    Hybrid GPT4o  0.191536  0.013577   0.841898
8    Dense Llama3  0.237334  0.028731   0.838726

In [4]:
retrieval_df = pd.DataFrame({

    "pipeline": [

        "Dense GPT4o",
        "Dense Llama3",
        "Dense Mistral",

        "Fusion GPT4o",
        "Fusion Llama3",
        "Fusion Mistral",

        "Hybrid GPT4o",
        "Hybrid Llama3",
        "Hybrid Mistral"

    ],

    "latency_seconds": [

        2.37,
        27.12,
        34.92,

        3.09,
        43.53,
        55.97,

        2.08,
        26.12,
        37.48

    ],

    "memory_mb": [

        0.03,
        46.06,
        6.81,

        75.11,
        -8.75,
        -5.07,

        8.35,
        24.37,
        -1.61

    ],

    "context_length": [

        2143.35,
        2143.35,
        2143.20,

        4541.65,
        4615.55,
        4714.35,

        2226.05,
        2226.05,
        2226.20

    ],

    "response_length": [

        673.95,
        701.80,
        668.15,

        734.80,
        947.45,
        791.05,

        550.85,
        823.65,
        679.65

    ],

    "context_relevance": [

        0.5622,
        0.5622,
        0.5615,

        0.5417,
        0.5390,
        0.5464,

        0.5587,
        0.5587,
        0.5589

    ]

})

retrieval_df

,pipeline,latency_seconds,memory_mb,context_length,response_length,context_relevance
0,Dense GPT4o,2.37,0.03,2143.35,673.95,0.5622
1,Dense Llama3,27.12,46.06,2143.35,701.80,0.5622
2,Dense Mistral,34.92,6.81,2143.20,668.15,0.5615
3,Fusion GPT4o,3.09,75.11,4541.65,734.80,0.5417
4,Fusion Llama3,43.53,-8.75,4615.55,947.45,0.5390
5,Fusion Mistral,55.97,-5.07,4714.35,791.05,0.5464
6,Hybrid GPT4o,2.08,8.35,2226.05,550.85,0.5587
7,Hybrid Llama3,26.12,24.37,2226.05,823.65,0.5587
8,Hybrid Mistral,37.48,-1.61,2226.20,679.65,0.5589

In [5]:
final_df = generation_df.merge(

    retrieval_df,

    on="pipeline",

    how="inner"

)

final_df

,pipeline,ROUGE_L,BLEU,BERTScore,latency_seconds,memory_mb,context_length,response_length,context_relevance
0,Fusion GPT4o,0.297738,0.047550,0.858821,3.09,75.11,4541.65,734.80,0.5417
1,Hybrid Mistral,0.271151,0.038345,0.851480,37.48,-1.61,2226.20,679.65,0.5589
2,Fusion Mistral,0.268982,0.039257,0.849840,55.97,-5.07,4714.35,791.05,0.5464
3,Dense GPT4o,0.238544,0.031553,0.847399,2.37,0.03,2143.35,673.95,0.5622
4,Dense Mistral,0.243224,0.022643,0.847247,34.92,6.81,2143.20,668.15,0.5615
5,Fusion Llama3,0.243026,0.035281,0.845276,43.53,-8.75,4615.55,947.45,0.5390
6,Hybrid Llama3,0.238935,0.037905,0.843333,26.12,24.37,2226.05,823.65,0.5587
7,Hybrid GPT4o,0.191536,0.013577,0.841898,2.08,8.35,2226.05,550.85,0.5587
8,Dense Llama3,0.237334,0.028731,0.838726,27.12,46.06,2143.35,701.80,0.5622

In [6]:
final_df["Overall_Rank"] = (

    final_df["BERTScore"]

    .rank(

        ascending=False,

        method="dense"

    )

)

final_df = final_df.sort_values(

    by="Overall_Rank"

)

final_df

,pipeline,ROUGE_L,BLEU,BERTScore,latency_seconds,memory_mb,context_length,response_length,context_relevance,Overall_Rank
0,Fusion GPT4o,0.297738,0.047550,0.858821,3.09,75.11,4541.65,734.80,0.5417,1.0
1,Hybrid Mistral,0.271151,0.038345,0.851480,37.48,-1.61,2226.20,679.65,0.5589,2.0
2,Fusion Mistral,0.268982,0.039257,0.849840,55.97,-5.07,4714.35,791.05,0.5464,3.0
3,Dense GPT4o,0.238544,0.031553,0.847399,2.37,0.03,2143.35,673.95,0.5622,4.0
4,Dense Mistral,0.243224,0.022643,0.847247,34.92,6.81,2143.20,668.15,0.5615,5.0
5,Fusion Llama3,0.243026,0.035281,0.845276,43.53,-8.75,4615.55,947.45,0.5390,6.0
6,Hybrid Llama3,0.238935,0.037905,0.843333,26.12,24.37,2226.05,823.65,0.5587,7.0
7,Hybrid GPT4o,0.191536,0.013577,0.841898,2.08,8.35,2226.05,550.85,0.5587,8.0
8,Dense Llama3,0.237334,0.028731,0.838726,27.12,46.06,2143.35,701.80,0.5622,9.0

In [7]:
final_df.to_csv(

    "Final_Project_Results.csv",

    index=False

)

print(
    "CSV Saved Successfully"
)

CSV Saved Successfully

In [9]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [10]:
final_df.to_excel(

    "Final_Project_Results.xlsx",

    index=False

)

print(
    "Excel Saved Successfully"
)

Excel Saved Successfully

In [11]:
final_df["memory_mb"] = final_df["memory_mb"].clip(lower=0)

In [12]:
final_df

,pipeline,ROUGE_L,BLEU,BERTScore,latency_seconds,memory_mb,context_length,response_length,context_relevance,Overall_Rank
0,Fusion GPT4o,0.297738,0.047550,0.858821,3.09,75.11,4541.65,734.80,0.5417,1.0
1,Hybrid Mistral,0.271151,0.038345,0.851480,37.48,0.00,2226.20,679.65,0.5589,2.0
2,Fusion Mistral,0.268982,0.039257,0.849840,55.97,0.00,4714.35,791.05,0.5464,3.0
3,Dense GPT4o,0.238544,0.031553,0.847399,2.37,0.03,2143.35,673.95,0.5622,4.0
4,Dense Mistral,0.243224,0.022643,0.847247,34.92,6.81,2143.20,668.15,0.5615,5.0
5,Fusion Llama3,0.243026,0.035281,0.845276,43.53,0.00,4615.55,947.45,0.5390,6.0
6,Hybrid Llama3,0.238935,0.037905,0.843333,26.12,24.37,2226.05,823.65,0.5587,7.0
7,Hybrid GPT4o,0.191536,0.013577,0.841898,2.08,8.35,2226.05,550.85,0.5587,8.0
8,Dense Llama3,0.237334,0.028731,0.838726,27.12,46.06,2143.35,701.80,0.5622,9.0